name: Security Vulnerability
description: Report a security vulnerability
title: "[Security]: "
labels: ["security", "priority:critical"]
body:
  - type: markdown
    attributes:
      value: |
        **Important:** For critical vulnerabilities, consider using private disclosure via SECURITY.md instead.

  - type: dropdown
    id: vulnerability-type
    attributes:
      label: Vulnerability Type
      options:
        - Path Traversal
        - SSRF (Server-Side Request Forgery)
        - XSS (Cross-Site Scripting)
        - Injection (SQL, Command, Prompt)
        - Authentication/Authorization
        - Information Disclosure
        - Denial of Service
        - Dependency Vulnerability
        - Other
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - Critical - Remote code execution, data breach
        - High - Privilege escalation, significant data exposure
        - Medium - Limited impact, requires specific conditions
        - Low - Minor information disclosure, defense in depth
    validations:
      required: true

  - type: textarea
    id: affected-files
    attributes:
      label: Affected Files
      description: Which files/components are affected?
      placeholder: |
        - src/api/routes.py (line 42)
        - src/jobs/runner.py (line 150)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the vulnerability in detail
    validations:
      required: true

  - type: textarea
    id: poc
    attributes:
      label: Proof of Concept
      description: Steps or code to reproduce the vulnerability
      render: shell
    validations:
      required: false

  - type: textarea
    id: fix
    attributes:
      label: Suggested Fix
      description: How should this be fixed?
    validations:
      required: false
