"""
Unit tests for src/crawler/filter.py

Generated by OpenCode 🤖 (AI assistant) with human review.
This code was created through AI-assisted development and reviewed by a human developer.

Tests cover:
- URL domain filtering
- Extension filtering
- Pattern filtering  
- Language detection and filtering
- Deduplication
- Edge cases
"""

import pytest

from src.crawler.filter import (
    filter_urls,
    _matches_language,
    EXCLUDED_EXTENSIONS,
    EXCLUDED_PATTERNS,
    LANGUAGE_PATTERNS,
)


class TestFilterUrls:
    """Test filter_urls function."""

    def test_filters_different_domain(self):
        """URLs from different domains should be excluded."""
        urls = [
            "https://example.com/page1",
            "https://other.com/page2",
            "https://example.com/page3",
        ]
        result = filter_urls(urls, "https://example.com/")
        assert len(result) == 2
        assert "https://example.com/page1" in result
        assert "https://example.com/page3" in result
        assert "https://other.com/page2" not in result

    def test_filters_different_subpath(self):
        """URLs outside base path should be excluded."""
        urls = [
            "https://example.com/docs/page1",
            "https://example.com/blog/post1",
            "https://example.com/docs/page2",
        ]
        result = filter_urls(urls, "https://example.com/docs/")
        assert len(result) == 2
        assert "https://example.com/docs/page1" in result
        assert "https://example.com/docs/page2" in result

    def test_filters_excluded_extensions(self):
        """URLs with excluded extensions should be filtered."""
        urls = [
            "https://example.com/page.html",
            "https://example.com/file.pdf",
            "https://example.com/image.png",
            "https://example.com/video.mp4",
        ]
        result = filter_urls(urls, "https://example.com/")
        assert len(result) == 1
        assert "https://example.com/page.html" in result

    def test_filters_excluded_patterns(self):
        """URLs matching excluded patterns should be filtered."""
        urls = [
            "https://example.com/docs/guide",
            "https://example.com/blog/post1",
            "https://example.com/changelog/v1",
            "https://example.com/api-reference/endpoint",
        ]
        result = filter_urls(urls, "https://example.com/")
        assert len(result) == 1
        assert "https://example.com/docs/guide" in result

    def test_deduplicates_urls(self):
        """Duplicate URLs should be deduplicated."""
        urls = [
            "https://example.com/page",
            "https://example.com/page",
            "https://example.com/page/",
        ]
        result = filter_urls(urls, "https://example.com/")
        assert len(result) == 1

    def test_normalizes_trailing_slash(self):
        """URLs with and without trailing slash should normalize to same."""
        urls = [
            "https://example.com/page/",
            "https://example.com/page",
        ]
        result = filter_urls(urls, "https://example.com/")
        assert len(result) == 1

    def test_returns_sorted_results(self):
        """Results should be sorted alphabetically."""
        urls = [
            "https://example.com/z-page",
            "https://example.com/a-page",
            "https://example.com/m-page",
        ]
        result = filter_urls(urls, "https://example.com/")
        assert result == sorted(result)

    def test_empty_input_returns_empty(self):
        """Empty input should return empty list."""
        result = filter_urls([], "https://example.com/")
        assert result == []

    def test_all_urls_filtered_returns_empty(self):
        """If all URLs are filtered out, return empty list."""
        urls = [
            "https://other.com/page1",
            "https://example.com/file.pdf",
        ]
        result = filter_urls(urls, "https://example.com/")
        assert result == []


class TestLanguageFiltering:
    """Test language filtering logic."""

    def test_default_english_only(self):
        """Default language filter should only include English URLs."""
        urls = [
            "https://example.com/en/guide",
            "https://example.com/es/guia",
            "https://example.com/fr/guide",
            "https://example.com/docs/page",  # No language pattern
        ]
        result = filter_urls(urls, "https://example.com/", language="en")
        assert len(result) == 2
        assert "https://example.com/en/guide" in result
        assert "https://example.com/docs/page" in result  # No pattern = included

    def test_spanish_language(self):
        """Spanish language filter should only include Spanish URLs."""
        urls = [
            "https://example.com/en/guide",
            "https://example.com/es/guia",
            "https://example.com/es-es/guia",
            "https://example.com/docs/page",
        ]
        result = filter_urls(urls, "https://example.com/", language="es")
        assert len(result) == 3
        assert "https://example.com/es/guia" in result
        assert "https://example.com/es-es/guia" in result
        assert "https://example.com/docs/page" in result

    def test_all_languages_mode(self):
        """language='all' should not filter by language."""
        urls = [
            "https://example.com/en/guide",
            "https://example.com/es/guia",
            "https://example.com/zh/guide",
        ]
        result = filter_urls(urls, "https://example.com/", language="all")
        assert len(result) == 3

    def test_matches_language_en_patterns(self):
        """Test English language pattern matching."""
        assert _matches_language("/en/guide", "en") is True
        assert _matches_language("/en-us/docs", "en") is True
        assert _matches_language("/en-gb/docs", "en") is True
        assert _matches_language("/english/page", "en") is True

    def test_matches_language_excludes_other_langs(self):
        """URLs with other language patterns should be excluded."""
        assert _matches_language("/es/guia", "en") is False
        assert _matches_language("/fr/guide", "en") is False
        assert _matches_language("/zh/guide", "en") is False
        assert _matches_language("/ja/guide", "en") is False

    def test_matches_language_no_pattern_includes(self):
        """URLs without language pattern should be included."""
        assert _matches_language("/docs/guide", "en") is True
        assert _matches_language("/api/endpoint", "es") is True
        assert _matches_language("/tutorial", "fr") is True

    def test_matches_language_case_insensitive(self):
        """Language patterns should match case-insensitively."""
        assert _matches_language("/EN/guide", "en") is True
        assert _matches_language("/En-Us/docs", "en") is True
        assert _matches_language("/ES/guia", "en") is False

    def test_chinese_variants(self):
        """Test Chinese language variants."""
        assert _matches_language("/zh/guide", "zh") is True
        assert _matches_language("/zh-cn/guide", "zh") is True
        assert _matches_language("/zh-tw/guide", "zh") is True
        assert _matches_language("/chinese/page", "zh") is True

    def test_japanese_patterns(self):
        """Test Japanese language patterns."""
        assert _matches_language("/ja/guide", "ja") is True
        assert _matches_language("/jp/guide", "ja") is True
        assert _matches_language("/japanese/page", "ja") is True

    def test_unknown_language_fallback(self):
        """Unknown language should use fallback pattern."""
        assert _matches_language("/nl/guide", "nl") is True
        assert _matches_language("/it/guide", "it") is True


class TestExtensionFiltering:
    """Test extension filtering."""

    def test_excludes_pdfs(self):
        """PDF files should be excluded."""
        urls = ["https://example.com/doc.pdf", "https://example.com/page"]
        result = filter_urls(urls, "https://example.com/")
        assert len(result) == 1
        assert "https://example.com/page" in result

    def test_excludes_images(self):
        """Image files should be excluded."""
        urls = [
            "https://example.com/image.png",
            "https://example.com/photo.jpg",
            "https://example.com/icon.gif",
            "https://example.com/page",
        ]
        result = filter_urls(urls, "https://example.com/")
        assert len(result) == 1

    def test_excludes_archives(self):
        """Archive files should be excluded."""
        urls = [
            "https://example.com/file.zip",
            "https://example.com/file.tar.gz",
            "https://example.com/page",
        ]
        result = filter_urls(urls, "https://example.com/")
        assert len(result) == 1

    def test_excludes_executables(self):
        """Executable files should be excluded."""
        urls = [
            "https://example.com/app.exe",
            "https://example.com/installer.dmg",
            "https://example.com/page",
        ]
        result = filter_urls(urls, "https://example.com/")
        assert len(result) == 1

    def test_extension_case_insensitive(self):
        """Extension filtering should be case-insensitive."""
        urls = [
            "https://example.com/file.PDF",
            "https://example.com/image.PNG",
            "https://example.com/page",
        ]
        result = filter_urls(urls, "https://example.com/")
        assert len(result) == 1


class TestPatternFiltering:
    """Test pattern filtering."""

    def test_excludes_blog(self):
        """Blog paths should be excluded."""
        urls = [
            "https://example.com/blog/post1",
            "https://example.com/docs/guide",
        ]
        result = filter_urls(urls, "https://example.com/")
        assert len(result) == 1
        assert "https://example.com/docs/guide" in result

    def test_excludes_changelog(self):
        """Changelog paths should be excluded."""
        urls = [
            "https://example.com/changelog/v1.0",
            "https://example.com/docs/guide",
        ]
        result = filter_urls(urls, "https://example.com/")
        assert len(result) == 1

    def test_excludes_api_reference(self):
        """API reference paths should be excluded."""
        urls = [
            "https://example.com/api-reference/endpoint",
            "https://example.com/docs/guide",
        ]
        result = filter_urls(urls, "https://example.com/")
        assert len(result) == 1

    def test_pattern_case_insensitive(self):
        """Pattern filtering should be case-insensitive."""
        urls = [
            "https://example.com/BLOG/post1",
            "https://example.com/Changelog/v1",
            "https://example.com/page",
        ]
        result = filter_urls(urls, "https://example.com/")
        assert len(result) == 1


class TestEdgeCases:
    """Test edge cases and special scenarios."""

    def test_handles_query_params(self):
        """URLs with query params should be preserved."""
        urls = ["https://example.com/page?foo=bar&baz=qux"]
        result = filter_urls(urls, "https://example.com/")
        assert len(result) == 1

    def test_handles_fragments(self):
        """URLs with fragments should be handled."""
        urls = ["https://example.com/page#section"]
        result = filter_urls(urls, "https://example.com/")
        assert len(result) == 1

    def test_handles_port_numbers(self):
        """URLs with port numbers should be handled."""
        urls = [
            "https://example.com:8080/page1",
            "https://example.com:8080/page2",
        ]
        result = filter_urls(urls, "https://example.com:8080/")
        assert len(result) == 2

    def test_different_ports_filtered(self):
        """URLs with different ports should be filtered."""
        urls = [
            "https://example.com:8080/page1",
            "https://example.com:9090/page2",
        ]
        result = filter_urls(urls, "https://example.com:8080/")
        assert len(result) == 1

    def test_subdomain_filtering(self):
        """Subdomains should be treated as different domains."""
        urls = [
            "https://docs.example.com/page1",
            "https://blog.example.com/page2",
            "https://docs.example.com/page3",
        ]
        result = filter_urls(urls, "https://docs.example.com/")
        assert len(result) == 2

    def test_complex_url_structure(self):
        """Complex nested URL structures should be handled."""
        urls = [
            "https://example.com/docs/v1/guide/install",
            "https://example.com/docs/v1/guide/config",
            "https://example.com/docs/v2/guide/install",
        ]
        result = filter_urls(urls, "https://example.com/docs/")
        assert len(result) == 3

    def test_prefix_false_positive(self):
        """Path prefix check must not include similarly-named sibling paths.

        Regression: /intune-for-education/ should NOT match base /intune/
        """
        urls = [
            "https://learn.microsoft.com/es-mx/intune/overview",
            "https://learn.microsoft.com/es-mx/intune/enrollment/enroll-android",
            "https://learn.microsoft.com/es-mx/intune-for-education/what-is-intune-for-education",
            "https://learn.microsoft.com/es-mx/intune-education/dashboard-intro",
            "https://learn.microsoft.com/es-mx/azure/virtual-machines/overview",
        ]
        result = filter_urls(urls, "https://learn.microsoft.com/es-mx/intune/", language="all")
        assert "https://learn.microsoft.com/es-mx/intune/overview" in result
        assert "https://learn.microsoft.com/es-mx/intune/enrollment/enroll-android" in result
        assert "https://learn.microsoft.com/es-mx/intune-for-education/what-is-intune-for-education" not in result
        assert "https://learn.microsoft.com/es-mx/intune-education/dashboard-intro" not in result
        assert "https://learn.microsoft.com/es-mx/azure/virtual-machines/overview" not in result
        assert len(result) == 2


class TestIntegrationScenarios:
    """Integration tests for realistic filtering scenarios."""

    def test_realistic_docs_site(self):
        """Test filtering a realistic documentation site."""
        urls = [
            "https://docs.example.com/en/guide/intro",
            "https://docs.example.com/en/guide/install",
            "https://docs.example.com/es/guia/intro",
            "https://docs.example.com/blog/release-v2",
            "https://docs.example.com/api-reference/overview",
            "https://docs.example.com/downloads/package.zip",
            "https://docs.example.com/en/api/endpoint",
        ]
        result = filter_urls(urls, "https://docs.example.com/", language="en")
        assert len(result) == 3
        assert "https://docs.example.com/en/guide/intro" in result
        assert "https://docs.example.com/en/guide/install" in result
        assert "https://docs.example.com/en/api/endpoint" in result

    def test_multilingual_site_all_languages(self):
        """Test multilingual site with all languages enabled."""
        urls = [
            "https://docs.example.com/en/guide",
            "https://docs.example.com/es/guia",
            "https://docs.example.com/fr/guide",
            "https://docs.example.com/zh/guide",
        ]
        result = filter_urls(urls, "https://docs.example.com/", language="all")
        assert len(result) == 4

    def test_mixed_extensions_and_patterns(self):
        """Test site with mixed extensions and patterns."""
        urls = [
            "https://example.com/docs/guide.pdf",
            "https://example.com/docs/guide.html",
            "https://example.com/blog/tutorial.pdf",
            "https://example.com/tutorial/index.html",
            "https://example.com/assets/logo.png",
        ]
        result = filter_urls(urls, "https://example.com/")
        assert len(result) == 2
        assert "https://example.com/docs/guide.html" in result
        assert "https://example.com/tutorial/index.html" in result
